## NUMPY:

...

Numpy arrays is like a python lists
Numpy array is a central data structure of the numpy lib
This lib is actually short for 'Numeric Python' or 'Numerical Python'

In [7]:
lst=[1,2,3,4]
print(lst)

[1, 2, 3, 4]


In [4]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array)
print(array.shape)
print(array.dtype)

[1 2 3 4]
(4,)
int32


In [8]:
lst=[1,2,3,4]
array=np.array(lst)
array=array+10
print(array)

[11 12 13 14]


In [10]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(3,4),(5,6)])
print(a2.shape)

(2, 3)
(3, 2)


## NUMPY(Reshape)

In [14]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(3,4),(5,6)])
print(a2.shape)
a1.reshape(3,2)



(2, 3)
(3, 2)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [18]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [19]:
a1=np.random.normal(5,0.5,20)
print(a1)

[5.06237155 4.65752211 4.78082845 5.15269588 6.06382547 4.53854917
 3.98367831 4.50568038 5.05058411 5.68391299 6.0909578  4.76921986
 6.16174033 5.56367774 5.4014232  5.94357795 4.83021825 5.15678963
 5.01938716 4.24438816]


In [20]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [24]:
np.zeros((2,2),dtype=np.int64)

array([[0, 0],
       [0, 0]], dtype=int64)

In [28]:
np.ones((4,3),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [29]:
a1=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(a1)[2]=5
print(a1)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [30]:
a1=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(a1)[1][3]=14
np.asarray(a1)[3][3]=16
print(a1)

[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1 16]]


In [31]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing column:",a1[:,2])

slicing column: [3 6]


In [32]:
a1=np.array([(1,2,3),(4,5,6)])
print("rows and columns",a1[1,:2])

rows and columns [4 5]


In [33]:
a1=np.random.normal(5,1,10)
print(a1)
print("min value:",np.min(a1))
print("max value:",np.max(a1))
print("meanvalue:",np.mean(a1))
print("median value:",np.median(a1))


[4.36374995 6.25338135 6.31521614 4.85624462 5.10362673 4.94068456
 5.12142641 6.73436612 4.11136621 4.98239908]
min value: 4.111366212791224
max value: 6.734366116213372
meanvalue: 5.278246119076234
median value: 5.043012906284414


In [34]:
c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)

14

In [35]:
c1=np.array([(1,2),(3,4)])
c2=np.array([(3,4),(1,2)])s
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

In [37]:
import pandas as pd
dict={"name":["anil","akhil","dinesh","harsha","ajay","kranth"],
     "emailID":["anil@gmail.com","akhil@gmail.com","dinesh@gmail.com","harsha@gmail.com","ajay@gmail.com","kranth@gmail.com"],
     "mobile no.":[999,888,777,888,777,999],
     "address":["hyd","hyd","hyd","hyd","hyd","hyd"]}
b=pd.dataframe(dict)
print(b)

ImportError: cannot import name compat